### PR TITLE
Move docs to en/ directory

### PR DESCRIPTION
**Pull request by AndersonTorres**
It allows comparison between the directories and helps translations.

### CODE REVIEW

**Comment by klardotsh** [comment]
I need @daysgobye and @kdb424 to confirm what, if any, implications this has on the Boardsource-maintained kmkfw.io docs pages, which might (?) be autogenerated off the docs tree here. I'm cool with this in theory otherwise though.

**Review by kdb424 — APPROVED** [review]
@daysgobye or I will merge once automation is ready assuming there aren't any blockers like there are now. Otherwise, once that's resolved, we'll take care of merging. Thanks for cleaning up.

**Comment by AndersonTorres** [comment]
Rebase: done!

**Comment by AndersonTorres** [comment]
@kdb424 ping

Is there anything that needs to be done?

**Comment by kdb424** [comment]
> @kdb424 ping
> 
> Is there anything that needs to be done?

Waiting on @daysgobye to update the site to work with this structure is all.

**Comment by kdb424** [comment]
Merging. The site that was a blocker doesn't keep up to date with docs, and is a separate problem. Merging, and will resolve that issue another time. No need to hold this up.

**Pull request merged**
