### PR TITLE
Add support for alternate RGB LED types

### PR DESCRIPTION
**Pull request by Gadgetoid**
To demonstrate what I mean by the steps laid out in #192 I have thrown together a custom (as yet untested) APA102/DotStar LED driver that bitbangs the APA102 protocol onto the two pins given (as a tuple) by `rgb_pixel_pin`.

This involves minimal changes to `KMKKeyboard` but I've made some bigger changes to `RGB` in order to support it.

Crucially RGB's docstrings now do not mention "NeoPixel" since the term "RGB LED" is all-encompassing.

Additionally I have reduced the number of methods in the `RGB` class that directly manipulate the `neopixel` instance variable, reducing the surface area that needs implemented in a subclass. Right now a subclass need only implement `setup`, `show`, `set_rgb` and `set_rgb_fill`.

I noticed `_to_dict` also exists on `RGB` and exposes the `neopixel` variable, making it potentially something we'd want to overload for different drivers. However I can't see `_to_dict` being used anywhere, and the Python magic method name for coercion to a dictionary is `__dict__` anyway. Does this method serve a purpose I'd need to be mindful of when subclassing?

I've also brought some test fixtures into the mix here, since I used them at to do some basic due-diligence and catch any silly syntax errors (lockdown has me working with a pretty minimal setup so I need all the automation I can get to stop me being foolish). This may relate to #71 since I couldn't find any existing tests and it seems like there's only linting set up?

I submit this as a draft for your perusal and welcome feedback, since I appreciate I'm storming in here with only a limited amount of knowledge of your project/roadmap and suggesting completely tangential changes/features.

Cheers!

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Adding new dependencies to the Pipfile has regenerated Pipfile.lock which brought up a bunch of new isort errors that I've fixed in 78826d6046309b840c88e25df76b5a135e42cced

I chose to add this as a separate commit to highlight these changes, rather than rebasing it into "Set up tests for LED drivers"

They *seem* pretty reasonable, but such a huge change of CI packages in a PR feels pretty nasty.

I originally had "tox" set up, totally against the grain of your current workflow- I've added a rudimentary `pytest` setup into the `Makefile` now and it should run in your CI.

It would probably be more idiomatic to have `make test` and `make lint` part of separate GitHub Actions workflows, so tests still run in the case of linting errors.

**Comment by kdb424** [comment]
Sorry for the late reply. I like the changes in here. Supporting more LED types, as well as supporting a matrix system for per key lighting animations is planned "eventually" so thanks for taking this part up. As a heads up, we are trying to ready up this, quite massive, rework to the core at some point soon, and everything we can is getting moved out to modules to save ram for those not using features. This also helps us clean up kmk_keyboard.py by preventing the changes you are doing in there, and allow that to live in the same file. The RGB code that runs in the new way can be seen here, though I think what you have could be easily adapted to work with the new system, as not many changes were needed to get the master branch worked over to that system.

https://github.com/KMKfw/kmk_firmware/blob/topic-merge-keyboard-and-state-rebased/kmk/extensions/rgb.py

**Comment by Gadgetoid** [comment]
> we are trying to ready up this, quite massive, rework to the core at some point soon

Music to my ears, the `KMK_Keyboard` class handled and knew way too much about its child modules. I had to get.... uhhh.... *creative* to add a Matrix Scanner that didn't accept the standard set of constructor arguments: https://github.com/pimoroni/kmk_firmware/commit/8f82b395e1149693a28ad164b637886e40549e60

Though I notice this is still happening in your rework presently:

https://github.com/KMKfw/kmk_firmware/blob/af0324cf488907bd47246c99204c7db7ecae4d7d/kmk/kmk_keyboard.py#L329-L337

I mention it a bit here, too - https://github.com/KMKfw/kmk_firmware/issues/192

Behind the scenes I've actually bounced off this project somewhat since it was difficult to bend to my whims and - when I did get it up and running - was crashing... perhaps I was running into the very memory issues you're trying to fix, I didn't have the time to investigate. I'll try and spare the time to make another attempt when the core update is done!

**Comment by kdb424** [comment]
The new core is merged. This can be ported over at some point if you have the time, or I'll pick the work up if no one gets around to it.

**Pull request closed without merging**
