### PR TITLE
[BLE] Clear bonds

### PR DESCRIPTION
**Pull request by dzervas**
With the key `BT_CLEAR_BONDS` all of the stored bondings are cleared! :smile:

### CODE REVIEW

**Comment by kdb424** [comment]
Since this edits keycodes, can we please get a docs update. Either bluetooth can get it's own page, or it can simply be added to the full list and that's it.

**Comment by kdb424** [comment]
Looks good to me. Waiting on final review from @klardotsh

**Review by kdb424 — APPROVED** [review]
Clean merge. Seems good to go.

**Review by klardotsh — CHANGES_REQUESTED** [review]
This includes the commit from #165 - can we get a clean rebase of just `a6152c3` and `25e28a6`, the two intended commits here?

Otherwise this seems good to me, thanks!

**Comment by kdb424** [comment]
Seems like it has been resolved. Merging.

**Pull request merged**
