### PR TITLE
Fix two way uart

### PR DESCRIPTION
**Pull request by wildesteven**
These are the changes I made to use two way UART on my RP2040 Corne.  I added a check on `uart_flip` to support crossing TX and RX in hardware.  I added a header byte to the front of each UART message to confirm that the pin is not floating.  I only apply the `split_offset` when sending from right to left.

### CODE REVIEW

**Review by klardotsh — CHANGES_REQUESTED** [review]
almost all of this appears to be sane, however, this appears to regress the case where the right side of a split is the primary - eg the side plugged into the actual PC. this was previously handled (not sure if correctly, but _handled_, in theory) by `self._is_target`. is it possible to refactor this to preserve EEHands functionality?

**Comment by wildesteven** [comment]
I'm not sure what you mean.  It seems to work fine for me with either side as the primary, with or without EEHands.

**Comment by Tonasz** [comment]
What test case do you @klardotsh mean?
I have 2x Pico connected through USB (for serial port debug), and with GND and RX -> TX, TX -> RX connected and tested these situations:
1) both sides
`Split(split_side=SplitSide.RIGHT,data_pin=board.GP1,data_pin2=board.GP0,uart_flip=False,split_target_left=False)`
2) both sides
`Split(split_side=SplitSide.RIGHT,data_pin=board.GP1,data_pin2=board.GP0,uart_flip=False,split_target_left=True)`
(i checked that the working half really changed by checking encoder input - only main side can produce it currently)
3) `Split(split_side=SplitSide.LEFT,data_pin=board.GP1,data_pin2=board.GP0,uart_flip=True,split_target_left=True)` + `Split(split_side=SplitSide.RIGHT,data_pin=board.GP0,data_pin2=board.GP1,uart_flip=True,split_target_left=True)`
4) `Split(split_side=SplitSide.LEFT,data_pin=board.GP0,data_pin2=board.GP1,uart_flip=True,split_target_left=False)` + 
`Split(split_side=SplitSide.RIGHT,data_pin=board.GP1,data_pin2=board.GP0,uart_flip=True,split_target_left=False)`
And everything worked.
Bonus tests on my fork with custom UART that allowed me connecting RX -> RX, TX -> TX on RP2040 and I could make two-way communication in analogous situations (just adjusted passed pins).

**Comment by kdb424** [comment]
Closing in favor of #301. Thank you for your contribution!

**Pull request closed without merging**
