### PR TITLE
Fix dependency of TapDance on instantiated HoldTap

### PR DESCRIPTION
**Pull request by xs5871**
#1010

### CODE REVIEW

**Comment by claycooper** [comment]
I see #1010 mentioned documentation. Do any changes need to happen there? Did you look or do you want me to?

**Comment by xs5871** [comment]
No changes to the documentation are necessary. `TapDance` can now be used without `HoldTap`.

**Review by claycooper — APPROVED** [review]

**Comment by JamesToBoot** [comment]
👍

**Comment by JamesToBoot** [comment]
Hey @xs5871 
if you have a sec, can you briefly explain why the removal of the import KC and the changing of KC.HT to its own veriable/name (not sure what you would call that) removes TD dependancy on the HT? 

It is not obvious to me where the dependancy was.

**Comment by xs5871** [comment]
`KC.HT` is basically an alias for `HoldTapKey` that has been registered under the name "HT" in the keycode dictionary "KC" -- for convenient usage in keymaps. That alias is created during instantiation of `HoldTap` -> that was the dependency.
But `TapDance` doesn't have to use that alias, it can use the "original".

**Pull request merged**
