### PR TITLE
Add RapidFire module

### PR DESCRIPTION
**Pull request by Jawfish**
Implements a module that lets users hold a key to repeatedly send a tap.

### CODE REVIEW

**Review by xs5871 — COMMENTED** [review]
Overall pretty neat. Got some minor suggestions.

**Comment by xs5871** [comment]
Sorry that I didn't come up with this earlier: Did you model this after some "reference" implementation?
I'm asking because I keep stumbling over the `repeat` option thinking it refers to a maximum number of repeats, which of course doesn't make sense. In my opinion something like `interval`, `repeat_delay` or similar would be more obvious. I'm also considering here that humans generally tend to not read the entire documentation.
Similar argument with `wait`: in every other "delayed action" module we've used the term `timeout`. That's more for consistency than clarity.

**Comment by Jawfish** [comment]
Decided to rename `randomize` to `enable_interval_randomization` with the justification that the improvement in clarity is worth the tradeoff in verbosity since in most cases users would be using the default value anyway.

**Review by kdb424 — APPROVED** [review]
Looks pretty readable to me. I need to try this at some point, but really useful feature to have.

**Comment by xs5871** [comment]
Agreed. I'm happy with this.

**Pull request merged**
