### PR TITLE
Remove the `peg_oled_display` extension

### PR DESCRIPTION
**Pull request by xs5871**
Reasons for the removal:
* terrible performance
* poor code quality
* unmaintained / unsupported

Where applicable: replace with the officially supported `display` extension.

### CODE REVIEW

**Review by claycooper — APPROVED** [review]

**Comment by claycooper** [comment]
Thank you.

**Comment by regicidalplutophage** [comment]
I'm not against removing it, but maybe we should come up with an example that's basically the re-implementation of PEG OLED to use in affected boards.

**Comment by xs5871** [comment]
All boards in our repository that used it are "ported" as part of the commit. To the best of my ability at least; they only displayed the top most layer anyway.

**Comment by regicidalplutophage** [comment]
> they only displayed the top most layer anyway

I missed that detail about them.

LGTM!

**Review by regicidalplutophage — APPROVED** [review]

**Pull request merged**
