### PR TITLE
BLE Multiple Connections

### PR DESCRIPTION
**Pull request by dzervas**
Adds support for more than one simultaneously connected centrals. The keys `BT_NXT` and `BT_PRV` are added to pivot between the active connection (where to send the keystrokes)

### CODE REVIEW

**Comment by kdb424** [comment]
Any PR that changes keycodes requires a documentation update. I believe that this may have been missed on our initial bluetooth merge, but going forward, we do require this.

**Comment by kdb424** [comment]
Looks good to me. @klardotsh want any changes?

**Review by kdb424 — APPROVED** [review]
Seems clean to me. Approved

**Review by klardotsh — CHANGES_REQUESTED** [review]
I haven't *really* reviewed this yet but I'm holding it until it's either:

- cleanly rebased on `master` containing only the unique diff intended by this PR
OR
- #165 and #166 are merged, and the diff shrinks itself automatically

Mostly because it's difficult to review stacked PRs like this, and at least at surface level this seems like a potentially more invasive/intensive change than the other two

**Comment by dzervas** [comment]
lets just merge the other two first. There are a lot going on here indeed

**Comment by kdb424** [comment]
@dzervas Can we get resolve what has conflicts, and then I think this can be merged.

**Comment by kdb424** [comment]
@klardotsh Can review this fully now. Looks much cleaner.

**Review by klardotsh — APPROVED** [review]
I'm gonna be real here - I haven't read this deeply to understand all the implications or potential footguns. But this PR has been sitting here, and has been tested by @kdb424 in a real-world scenario, for long enough that I'm gonna YOLO merge this and we can tackle code cleanup or feature changes as follow-on issues in the future. For now, since we're not claiming to the world to be stable (beta since July 2019 CKEYS, y'all!), why not.

**Comment by dzervas** [comment]
BLE support is definitely not stable and needs more work - in general. I hope I'll find some time to continue working on it

**Comment by kdb424** [comment]
I am putting quite a bit of work into bluetooth, working on memory management, and powersave right now in another branch. It should be resolved soon enough.

**Pull request merged**
