### PR TITLE
Added missing keys on lily58

### PR DESCRIPTION
**Pull request by TellNoLies**
The lily58 keyboard main.py was missing the top row along with the center key on the thumb cluster. I added this in the layout but did not add any pins in kb.py. I was unsure what needed to be included.

### CODE REVIEW

**Comment by kdb424** [comment]
I'll accept your keymap as well if @klardotsh is fine as you also fixed an issue with it. I'll let them merge at their leisure.

**Review by kdb424 — APPROVED** [review]

**Comment by TellNoLies** [comment]
Lol. It was wrong. I had gotten carried away with a custom keymap that I
didn't realize that I was editing the wrong one. Plus I am not a programer,
so I am sure I have many mistakes in the config.

**Comment by kdb424** [comment]
@klardotsh Looking for a final review before merging.

**Comment by klardotsh** [comment]
no strong opinions here, so merging

**Comment by TellNoLies** [comment]
So, I was looking at the traces on my lilly58 to see why my layout wasn't working when I updated my keylayout. It seems that the keys I added to both left and right sides, on the fourth row belongs to the fifth row. I had a look at the tracers on the board and discovered this.
Do I need to submit another pull request?

**Comment by klardotsh** [comment]
you're welcome to push that change upstream in another PR yes!

**Pull request merged**
