### PR TITLE
Add Numerical Keypad support from Bolt Industries

### PR DESCRIPTION
**Pull request by davigupta**
Squashed the commits.

### CODE REVIEW

**Comment by xs5871** [comment]
Apologies for the recurring delay: linter is unhappy again.
(History is clean now, though. You can also force push a squashed rebase, no need to open a new PR)

**Comment by davigupta** [comment]
fixed the lint issue

make test
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
...............................................................
----------------------------------------------------------------------
Ran 63 tests in 15.287s

OK

**Comment by davigupta** [comment]
> Apologies for the recurring delay: linter is unhappy again. (History is clean now, though. You can also force push a squashed rebase, no need to open a new PR)

Fixed the lint issue.

**Comment by davigupta** [comment]
use old pull request 671

**Pull request closed without merging**
