### PR TITLE
unit tests for execution in desktop dev environment

### PR DESCRIPTION
**Pull request by honboubao**
I have added a few unit tests that can be executed without having a board at hand. There're still many features that aren't covered yet, but I guess it's a start.

### CODE REVIEW

**Review by klardotsh — APPROVED** [review]
nice, something like this existed in the first couple months of KMK's life back in 2018 but I could never really dedicate the time to making it actually worthwhile. this is a good start in that direction. cheers!

**Comment by klardotsh** [comment]
@honboubao if you could rebase and resolve the outstanding conflict, I'm ready to merge whenever it's ready

**Comment by honboubao** [comment]
Thanks for having a look at this. Should be ready to merge now.

**Comment by xs5871** [comment]
This currently breaks 'kmk.hid' during HID send and renders KMK unusable.
```
Traceback (most recent call last):
  File "code.py", line 6, in main
  File "kb.py", line 44, in go
  File "kmk/kmk_keyboard.py", line 382, in go
  File "kmk/kmk_keyboard.py", line 430, in _main_loop
  File "kmk/kmk_keyboard.py", line 102, in _send_hid
  File "kmk/hid.py", line 129, in send
AttributeError: 'bytearray' object has no attribute 'startswith'
```

circuitpythons `bytearray` doesn't implement 'startswith', just like the stacktrace says.

**Comment by honboubao** [comment]
really sorry about that... fix in #313

**Pull request merged**
