### PR TITLE
Add reverse scrolling mode to the Pimoroni Trackball module

### PR DESCRIPTION
**Pull request by slabua**
I added the good old reverse scrolling mode.

Scrolling parameter is optional, defaults to natural scrolling direction.

### CODE REVIEW

**Review by xs5871 — CHANGES_REQUESTED** [review]
Looks sensible, except we prefer enum-like objects instead of magic strings, something like this:
```python
class ScrollDirection:
    NATURAL = const(0)
    REVERSE = const(1)

# ...
if self.scrolling == ScrollDirection.REVERSE:
```

**Comment by slabua** [comment]
> Looks sensible, except we prefer enum-like objects instead of magic strings, something like this:
> 
> ```python
> class ScrollDirection:
>     NATURAL = const(0)
>     REVERSE = const(1)
> 
> # ...
> if self.scrolling == ScrollDirection.REVERSE:
> ```

Thanks, it looks much better indeed!
Code updated accordingly.

**Review by klardotsh — COMMENTED** [review]
Are there clearer terms than "natural" and "reverse" here? I take "Natural Scrolling" to mean what it does in, say, MacOS or ChromeOS (in that gesturing the tracking device downwards will move a document upwards), and "reverse" means nothing useful to me.

ChromeOS calls "down is up" scrolling "Australian" scrolling, which is a clever tongue-in-cheek (if Northern Hemisphere centric) way of disambiguating these things.

Which makes me think - maybe calling the constants "DOWN_IS_DOWN" and "DOWN_IS_UP" is clearer? Idk.

**Comment by klardotsh** [comment]
I also approved and ran tests here, which then failed the linter. `make fix-lint` is in order

**Comment by slabua** [comment]
> Are there clearer terms than "natural" and "reverse" here?
> [...]

I think those are the universally recognised terms for either type of scrolling.

> Which makes me think - maybe calling the constants "DOWN_IS_DOWN" and "DOWN_IS_UP" is clearer? Idk.

Maybe better to specify it explicitly, yes.

**Comment by slabua** [comment]
> I also approved and ran tests here, which then failed the linter. `make fix-lint` is in order

hm 🤔

**Comment by slabua** [comment]
Should I update the code with the clearer definitions of "DOWN_IS_DOWN" and "DOWN_IS_UP"?

**Comment by xs5871** [comment]
My 2 cents and not at all a strong opinion: I'd prefer the natural/reverse nomenclature. If "natural" is the default, then "reverse" is obvious.

On another note: what's your opinion on renaming the `scrolling` parameter to `scrolling_direction`?

**Comment by slabua** [comment]
> My 2 cents and not at all a strong opinion: I'd prefer the natural/reverse nomenclature. If "natural" is the default, then "reverse" is obvious.

Alrighty

> On another note: what's your opinion on renaming the `scrolling` parameter to `scrolling_direction`?

I agree on `scrolling_direction`, it is semantically more correct.

**Comment by slabua** [comment]
> I agree on `scrolling_direction`, it is semantically more correct.

 Perhaps `scroll_direction` then?

**Comment by slabua** [comment]
Code has been updated accordingly

**Review by xs5871 — APPROVED** [review]

**Pull request merged**
