### PR TITLE
Fix unittest

### PR DESCRIPTION
**Pull request by xs5871**
Pretty much a complete refactor of the keyboard emulation unittest + fixes to get everything working again.
Current version was impossible to read, had terrible debug output, and most importantly didn't do bjective comparisons of generated and desired keycode reports.
KC has an `__iter__` now, so we can do reverse lookups.

### CODE REVIEW

**Comment by xs5871** [comment]
Still don't understand why my local linter is sometimes different than the github one.

**Comment by xs5871** [comment]
The unittests run perfectly fine in my local environment... I don't understand this.

**Comment by xs5871** [comment]
Couldn't reproduce the issue locally reliably (had it once in the first of about 100 runs). Maybe some random race condition...
Not a great fix, but it seems to do the job. I welcome any further insights at this point.

**Comment by Jawfish** [comment]
Experiencing some strange behavior with this:
On Windows (Python 3.10.5), `python -m unittest` has 6 fails
On Ubuntu (Python 3.8.10), it has 1 fail (but `make test` passes)
On MacOS (Python 3.9.10), it has no fails
This happens consistently. Tested on a fresh clone of the repo.

The failed tests are:
`test_chord`, `test_sequence`, `test_holdtap_chain`, `test_oneshot`, `test_modtap` and `test_normal_key` on Windows, only `test_chord` in Ubuntu.

Seems to be some kind of timing issue.

**Comment by LukeDRussell** [comment]
I get failures on Windows 11 as well:
test_chord, test_sequence, test_oneshot, test_modtap, test_normal_key
All fail with `AssertionError: reports don't match up`

**Pull request merged**
