### PR TITLE
Add Pico87 board

### PR DESCRIPTION
**Pull request by hendrix04**

### CODE REVIEW

**Comment by xs5871** [comment]
There's some lint to be picked. You can most likely fix it automatically with `make fix-isort fix-formatting`.

**Comment by hendrix04** [comment]
So I was a bit confused by this because I definitely ran that before I submitted. Running it again only modifies kmk_firmware/boards/fingerpunch/ffkb/nice_nano/main.py which is a pre-existing lint issue. I had updated that in my initial PR, but figured that since I am limiting the scope here as much as possible, it would be better to leave it.

Could you point me towards the issues that you see?

**Comment by xs5871** [comment]
You can click on 'Details' here on github, or run `make tests` to get:
```
24 ./boards/Pico87/kb.py:43:1: W293 blank line contains whitespace
25 ./boards/Pico87/kb.py:43:1: BLK100 Black would make changes.
26 ./boards/Pico87/kb.py:43:5: W292 no newline at end of file
27 ./boards/Pico87/main.py:56:16: W292 no newline at end of file
```

**Review by kdb424 — APPROVED** [review]

**Comment by kdb424** [comment]
I'll let any maintainer disagree for a day or two, but otherwise I'll just merge next time I am on a merge spree if no one has complaints. Looks good to me.

**Pull request merged**
