### PR TITLE
Added more examples to the Stringy Keymaps documentation

### PR DESCRIPTION
**Pull request by moritz-john**
Following this issue: 
https://github.com/KMKfw/kmk_firmware/issues/669
[Zulip Chat Topic](https://kmkfw.zulipchat.com/#narrow/stream/358347-general/topic/Do.20layers.20MO.281.29.20work.20in.20StringyKeymaps.3F)

I felt the need to update the [Stringy Keymaps documentation](http://kmkfw.io/docs/extension_stringy_keymaps/).
In it's current form the documentation does not mention that it's possible to mix and match string-based key references and standard keycodes.

I added an example showcasing this.

___

The sentence
> Enables referring to keys by 'NAME' rather than KC.NAME.

may lead users to incorrectly assume it applies to layer keycodes like `KC.MO(layer)`, resulting in confusion as it needs to still be referenced using the notation of e.g. `KC.MO(1)` rather than `MO(1)`.

I also added a note for this.

### CODE REVIEW

**Comment by xs5871** [comment]
There's a pending change request still open.

**Comment by moritz-john** [comment]
Thank your for your reply.
> There's a pending change request still open.

May I ask which pending change request you are talking about?

**Review by xs5871 — CHANGES_REQUESTED** [review]

**Comment by xs5871** [comment]
I may have marked it as a question instead of a request for change. My bad.

**Comment by moritz-john** [comment]
No problem, I applied your suggested change I think.
It's the first time I have to deal with requested changes so I apologize if I make a mistake.

**Review by xs5871 — APPROVED** [review]
Perfect, thank you and apologies for the confusion!

**Pull request merged**
