### PR TITLE
Refactor pimoroni trackball

### PR DESCRIPTION
**Pull request by xs5871**
Various memory and performance improvements.
resolves: #649

### CODE REVIEW

**Review by claycooper — APPROVED** [review]

**Comment by xs5871** [comment]
@regicidalplutophage you ment to ask some questions about optimization. This would be a good opportunity, before we merge.

**Comment by regicidalplutophage** [comment]
> @regicidalplutophage you ment to ask some questions about optimization. This would be a good opportunity, before we merge.

My reluctance to review this stemmed from struggling to understand a good chunk of changes. I think gaining some experience and going through commits one by one helped

**Review by regicidalplutophage — APPROVED** [review]
I still don't understand the maths, but I'm fine with it.

**Comment by xs5871** [comment]
Assuming you mean the rotation matrix: that's a common way to represent 2D rotations (or higher dimensions in computer graphics, though slightly modified). Fundamentally it's just trigonometry expressed in the terms of linear algebra. The important part is that we calculate the rotation coefficients only once during initialization, instead of every cycle. It breaks down to reducing the amount of floating point calculations, because they're usually not done in hardware.
Let me know if that was somewhat of a satisfactory breakdown, or if I missed your question completely.

**Comment by regicidalplutophage** [comment]
The scary trig was moved to ```during_bootup```, got it

**Comment by xs5871** [comment]
Not scary, just misunderstood.

**Pull request merged**
