### PR TITLE
Re-formatted layer key creation to be consistent

### PR DESCRIPTION
**Pull request by claycooper**
Key creation formatting in layer module wasn't consistent across keys in the module or with key creation in other parts of the codebase.

### CODE REVIEW

**Comment by xs5871** [comment]
It is, however, consistent with the linters format rules. Your proposed change, though nicer to the human eye, unfortunately is not.

**Review by xs5871 — APPROVED** [review]
Clever use of punctuation.

**Comment by claycooper** [comment]
Thanks for the merge. I'm not good with git or linting and was thinking that was a test commit. I wanted to attempt a squash merge once I got the linter to succeed.

**Comment by xs5871** [comment]
The linter trips up everyone, no matter the experience. I could have rebase-squashed your commits in the github ui, but was a bit too trigger-happy on the merge button.

**Pull request merged**
