### PR TITLE
Cleanup debug

### PR DESCRIPTION
**Pull request by xs5871**
* Use the debug utility everywhere.
* Guard all debug statements.
* Remove the legacy `keyboard.debug_enabled` flag / property,
* and document debug utility usage instead

### CODE REVIEW

**Review by regicidalplutophage — CHANGES_REQUESTED** [review]
What about the KC.DEBUG in keys.py?

**Comment by regicidalplutophage** [comment]
Oops.
It was of limited use now that debug handler is gone. Maybe it should be reimplemented with a different functionality that makes sense?

**Comment by xs5871** [comment]
The debug handler isn't gone, the debug key had the same functionality just without the detour over `keyboard.debug_enabled`.

**Comment by regicidalplutophage** [comment]
I see now. I've gotten illiterate as of late.

**Pull request merged**
