### PR TITLE
Enhancement global pointing device

### PR DESCRIPTION
**Pull request by xs5871**
We're currently handling pointing device HIDs completely independent and agnostic of one another.
That requires duplicate code and when using more than one PD HID module, they interfere with each other.

This is an attempt to consolidate and build a central API for axis movement.
Mouse keys can be handled just like keyboard and consumer control keys. Unfortunately that doesn't work with axes, because they have continuous states (the amount of movement), not binary (pressed/released). I'm still undecided about the exact implementation details and open to suggestions.

### CODE REVIEW

**Comment by kdb424** [comment]
I'm in favour of this change. Obviously it needs tested and finished, but over all, good thought.

**Comment by xs5871** [comment]
@claycooper apologies... this is a big one.

**Review by claycooper — COMMENTED** [review]
mouse_keys.py has some commented out print statements. Do you want to clean them up before merging or leave them for future testing?

**Comment by xs5871** [comment]
From what I see it's the other way around. Old print comments have been removed.

**Review by claycooper — APPROVED** [review]
You're right. I switched apps before the final review and it must have swapped the order of the commits on me. Sorry about that.

**Pull request merged**
