### PR TITLE
updates for capsword

### PR DESCRIPTION
**Pull request by masiullah**
updates for capsword
opening as draft

### CODE REVIEW

**Comment by masiullah** [comment]
@xs5871 would you be able to provide some guidance on routing the modtap key actions via the process_key

**Comment by xs5871** [comment]
There's a `pre_process_key` pending that you will be able to use.

**Comment by kdb424** [comment]
No longer pending. It's in.

**Comment by masiullah** [comment]
Thanks @xs5871  and @kdb424

**Comment by masiullah** [comment]
> There's a `pre_process_key` pending that you will be able to use.
@xs5871 
Could you please let me know your thoughts of how the pre process key should be used w.r.t to the modules in question for this feature? Hopefully, I can take it forward once I am able to grasp the potential of this new addition

**Comment by xs5871** [comment]
Use it instead of `process_key`. It has the same signature, but it will apply all the modules `process_key`.

**Comment by masiullah** [comment]
Haven't got a chance to work on it, will reopen when I have some updates to it

**Pull request closed without merging**
