### PR TITLE
hold-tap-enhancements

### PR DESCRIPTION
**Pull request by xs5871**
This has been a requested feature (#278), and after using it for 2 days, rightfully so.
Just wanted you to know that this is being worked on.

### CODE REVIEW

**Comment by kdb424** [comment]
I like where this is going! Let us know if you need anything specific, but thank you for looking into this and testing. I'll try to get it tested as well on my boards.

**Comment by xs5871** [comment]
I think screwed up merging the master branch, sorry.
Anyway, last commit implements evaluation of hold-tap behavior on other key release, which seems to be the default in QMK/ZMK (for reference).
`prefer_hold` and `tap_interrupted` options aren't working with the layer module yet, as the interrupting key gets its keycode assigned before the layer switch is performed.

**Comment by kdb424** [comment]
Let us know when you are ready for review, and we'll get it looked at.

**Comment by xs5871** [comment]
The Layer module now also supports `prefer_hold` and `tap_interrupted`; more specifically layer tap/toggle (TT) uses `prefer_hold` as defaut instead of overloading `ht_(de)activate_on_interrupt`.
The `tap_interrupted` logic may be potentially controversial. It relies on suppressing keys and on release retroactively adding them to `keyboard._coordkeys_pressed`. That ensures consistent behavior even when the keys change identity after a layer change.

However: one of the commits ("fix permanent hid_send") currently regresses on #256/#257. I'd rather suggest a "more proper" fix in a separate PR addressing this issues than revert the commit. The fix is already implemented, I'll reference it here once published. That also means there's no need to review at this point in time.

Documentation will be updated next. Tapdance is predestined to use the same hold-tap backend, but is definitely going to be a separate feature branch.

**Comment by xs5871** [comment]
Should be ready for review, finally.

**Review by kdb424 — APPROVED** [review]
I'll give @klardotsh a day or two to refute anything here, otherwise looks good to me.

**Pull request merged**
