### PR TITLE
Updates to boot.py docs

### PR DESCRIPTION
**Pull request by HBBisenieks**
Just a little bit of massaging on the `boot.py` docs that were recently merged in to bring the page more in-line with the style used throughout the project.

### CODE REVIEW

**Comment by xs5871** [comment]
I generally approve, very much appreciated.
Would you mind rebasing your commits on the current master? May not be strictly necessary for this, but for more complex PRs it makes the history easier to follow.

On a minor, recent note: as it turns out, the `boot_device=1` setting doesn't always work, and we don't exactly know when and why. Didactically that's not very helpful, but it may spare some folks frustration if we put a note in the documentation until we figure that out.

**Comment by kdb424** [comment]
Once @xs5871 is happy, and approves, I'll get it merged!

**Comment by HBBisenieks** [comment]
> Would you mind rebasing your commits on the current master? May not be strictly necessary for this, but for more complex PRs it makes the history easier to follow.
Happy to in the future. Thanks for the reminder.

**Comment by kdb424** [comment]
Rebase is automatic on merge here unless there are conflicts. If you are comfortable rebasing, it's easier of course.

**Review by xs5871 — APPROVED** [review]

**Review by kdb424 — APPROVED** [review]

**Pull request merged**
