### PR TITLE
Goodbye, CLA!

### PR DESCRIPTION
**Pull request by klardotsh**
It's not particularly useful - we haven't run into any weirdness around contributions and it's a hurdle to contributing that shouldn't need to be there.

The bot and merge-blocking check have also been disabled.

### CODE REVIEW

**Comment by klardotsh** [comment]
RFC from @siddacious @tannewt and @elvis-epx

**Comment by kdb424** [comment]
@rk463345

**Comment by tannewt** [comment]
Fine with me!

**Comment by rk463345** [comment]
fine with me

**Comment by klardotsh** [comment]
Just waiting for approval from @elvis-epx

**Comment by elvis-epx** [comment]
Ok for me!

**Pull request merged**
