### PR TITLE
The Declaration of Independence (from the original, tricky implementation of KMK)

### PR DESCRIPTION
**Pull request by klardotsh**
This effectively reopens @kdb424's https://github.com/KMKfw/kmk_firmware/pull/189, which was his continuation efforts to mainline-ify the work I started clear back in late 2019, so I'm copying in the last remaining bit of his TODO list, and marking off fixes I've done:

- [ ] Add example on building a basic extension
- [x] Test that wired split keyboards can communicate between halves (@klardotsh: mostly confirmed - this comment is being typed primarily on an Iris Rev2 + NiceNano, though I have a few keys that are either hardware dead, or software bugs, sooooo.... unsure what's up)
- [ ] Test that wireless split keyboards can communicate between halves (I think I might be the only one between @kdb424 and I who has BT hardware still, but regardless of who does it, it needs tested before merge)

Would love to get feedback from @pullenrc, @gigahawk, and anyone else who has been tinkering on KMK recently, but ultimately we need to get this branch merged fairly soonish if possible so we stop leading people astray, having them build against the basically-deprecated, difficult, buggy, and slow `master`

### CODE REVIEW

**Comment by klardotsh** [comment]
There are... no logs at all for the CI failures, and I haven't seen logs on basically any CI failures for probably a year now. Ugh. Not something I feel like debugging tonight, but should probably get fixed sooner than later as well.

**Comment by klardotsh** [comment]
Just confirmed that my funky keys on this Iris were entirely hardware issues (hotswap keys weren't making contact with the sockets because the PCB was separating from the keys - fixed!) so wired splits appear to be working perfectly fine here; board is *very* responsive and boots up at least quicker than my M4-based, `master` branch Iris ever did

**Comment by kdb424** [comment]
Once we have all recent PR's that we took ported over to this branch, and we make notes of regressions (like lack of leader mode, ect), I vote we yolo merge it in, and clean up the issues. Dealing with "thing is broken/missing" than "test this other branch". If you can live on that for a week, and no one else has a good argument, let's just do this. We need to mark BT splits as BETA, and we can't offer a guarantee, but I believe that they *may* work, and they were in a pretty beta state last I left them. It "worked" but it was not smooth, seamless, or easy.

**Comment by klardotsh** [comment]
Cool, then we're saying 00:30 PDT (UTC-07:00) on 27 June 2021 is our merge deadline for this unless we find showstoppers? I'm cool with this, it's about time we get 'er done, I just want to make sure we're not merging total trash fires onto `master` if we can help it.

**Comment by klardotsh** [comment]
It occurs to me that https://github.com/KMKfw/kmk_firmware#getting-started is super outdated, and should be updated as part of this branch (if it isn't already, and even if it was touched in the fall, things have changed even since then).

**Comment by Gigahawk** [comment]
Is there anything in that section that's actually out of date other than the CPy version?

I think it's fine that it doesn't mention kmk_python given that it's out of date and likely won't have any work done on it until CPy 7 is stable

**Comment by klardotsh** [comment]
IIRC KMKPython targets 6.x and is required on some (particularly small) boards that use Bluetooth. @kdb424 is more of the domain expert on this than I am.

**Comment by kdb424** [comment]
Bluetooth "issue" is handle in the bluetooth sections, and the MCU list can get an update sure, but honestly, there's more boards we support than don't these days.

**Comment by kdb424** [comment]
As for examples of writing basic extensions, the LED example is a good real world example of this, as is powersave. When someone that is better at writing docs than myself wants to add them, it would be great, but we have good, simple, code examples. Bluetooth splits have been marked Alpha as they "work" but are buggy, and not in a state I'm comfortable with supporting, but do type. This can be resolved going forward as the core is the important change, and that feature should have been a separate merge, but it's fine as alpha.

**Review by kdb424 — APPROVED** [review]
There will be issues opened after this, but it looks clean to me. Ready to merge and deal with the slurry of confusion inbound.

**Comment by klardotsh** [comment]
After behind the scenes discussion with @kdb424 we've agreed the best path for KMK is to just merge this dang thing finally, and we'll handle the spot cleaning, detailing, and any small bugs (ex. #206) in follow-up PRs: it hurts the project (and all the new folks discovering it!) more to "advertise" the current master branch than it does to merge something 99% cleaner, but maybe 95% stable. I'll take that 5% risk.

Thanks to @kdb424 for picking up my original designs and porting most of the extensions/modules over, and to the several contributors who have been building against this branch in forks and filing issues against it (a few of which are fixed, and a few will be soon) - hopefully the new API design is easier to work with, more predictable, and brings the understandability of the core up a bit!

**Pull request merged**
