### PR TITLE
Encoders!

### PR DESCRIPTION
**Pull request by pullenrc**
Integrated encoder functionality.  Tested and working on a teensy 4.1

### CODE REVIEW

**Comment by klardotsh** [comment]
Gonna recommend holding tight on this one - the base branch is still being rebased and force-pushed a bunch, and I don't want you to have to go through interactive rebase hell 9000 times in the next couple of days

**Comment by pullenrc** [comment]
I am just reading through the modules/extension features right now, makes sense that encoders would be a module, I'll start working in that.

**Comment by klardotsh** [comment]
Oh, this auto closed.... lol. Go ahead and re-open this against `master` whenever you're ready, now that #207 merged and the official KMK implementation is *finally* that refactor :tada:

**Comment by pullenrc** [comment]
Alright, I may just hold off until it’s ready as a module.

Ryan Pullen



On Jun 25, 2021, at 1:52 PM, Josh Klar ***@***.***> wrote:

﻿

Oh, this auto closed.... lol. Go ahead and re-open this against master whenever you're ready, now that #207<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKMKfw%2Fkmk_firmware%2Fpull%2F207&data=04%7C01%7C%7Cd8a188c79dd54fdb5cec08d9380a6b9c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637602439663294714%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=t3Uh5YnjjWNtBHJBTcr%2FH%2FXd6OKPrgwWtxWGP3QVvxo%3D&reserved=0> merged and the official KMK implementation is finally that refactor 🎉

**Comment by kdb424** [comment]
Modules should be insanely easy to add against compared to the old system. Most of the code ports directly over. Look at the LED for a simple example.

**Comment by pullenrc** [comment]
Will do, thanks for the work guys.

Ryan Pullen



On Jun 25, 2021, at 2:00 PM, Kyle Brown ***@***.***> wrote:

﻿

Modules should be insanely easy to add against compared to the old system. Most of the code ports directly over. Look at the LED for a simple example.

**Pull request closed without merging**
