### PR TITLE
Enhancement rgb

### PR DESCRIPTION
**Pull request by xs5871**
relates to #224. Implements:
- use common clamping function in incrementing/decrementing methods
- faster HSV to RGB conversion
- make neopixel lib only necessery for default pixelbuffer

HSV domain has been changed from [0-360, 0-100, 0-100] to [0-255, 0-255, 0-255]. Makes the math easier and faster for 16 bit fixed point calculations.

### CODE REVIEW

**Comment by kdb424** [comment]
While I love most of this, I do wonder if we are going to lose any actually noticeable range of RGB by clamping to 255 instead of 360 that gets lost. I like the perf that we gain, but would like to see if anyone else notices, or misses that extra colour range (mostly in hue, not sat/val)

**Comment by xs5871** [comment]
That is a fair point and something I considered.
The missing color resolution isn't really humanly noticeable for static colors, especially since common RGB LEDs aren't that color accurate anyway and we're not dealing with color accurate print media, for example. Jumps in brightness are much more noticable (from a perception point of view), and we'll have some rounding errors some way or another, if we don't want to use floats. Unless we use at least 24 bits for each axis, but I think that's overkill for our use. Value and Saturation have a higher impact than Hue on smooth color transitions as soon as they aren't at 100%.
The [255, 255, 255] range is standard/common for embedded systems, so that's what I went with.

**Comment by kdb424** [comment]
Purely anecdotal, but without the PR, I noticed a wide range of blue, but the red range felt insanely shallow if that makes sense. I haven't tested this on hardware yet, but on the swirl animation, this was very noticeable. I'll be sure to test on real hardware and give in a look. I agree that resolution doesn't have to be hyper accurate, but seeing that some things already felt compressed, I had the jerk reaction. I'm sure it's something you tested though already, and you have proven to know what you are doing. Once I get a chance to test on hardware, code looks clean. I'll try to have it merged by end of weekend at the latest.

**Comment by xs5871** [comment]
The "original" KMK implementation didn't use the full range of 255 values for each RGB channel, but capped out at 100. I only noticed it because of the refactor and assumed that was an oversight. The non-linearity of neopixels and absence of any kind of gamma correction may very well result in the effect you describe. The apparent brightness of the red and green channel of WS2818 is much, much less than the blue one; even more so if you turn down the brightness.

**Comment by kdb424** [comment]
Well that explains a lot. I won't lie, I wrote that HSV to RGB after learning the math, noticed it mostly worked, and shipped it. Sounds like you didn't remove any functionality then over my flawed implementation. Code looks clean, and that checks out. Merging.

**Review by kdb424 — APPROVED** [review]

**Pull request merged**
