### PR TITLE
Brazilian Portuguese Translations- Finished

### PR DESCRIPTION
**Pull request by AndersonTorres**

### CODE REVIEW

**Comment by kdb424** [comment]
Thanks again for getting all of this! I'll give it a once over, and get it merged soon.

**Review by kdb424 — APPROVED** [review]

**Comment by kdb424** [comment]
Let us know when you think you are done, and we'll get a proper review in.

**Comment by AndersonTorres** [comment]
@kdb424 now it is done! All files from `docs/*.md` are translated to ptBR.

**Comment by klardotsh** [comment]
I'll jump in for the legal shenanigans and leave content review to @kdb424.

The default license for all documentation in the repo is [Creative Commons BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) as seen [in the README](https://github.com/KMKfw/kmk_firmware#license-copyright-and-legal), so we can either continue to solely use that implied license, or if you prefer to **dual license this additionally** into the public domain, you're welcome to add a [Creative Commons Zero 1.0](https://creativecommons.org/publicdomain/zero/1.0/) hint (via an [SPDX identifier](https://spdx.dev/ids/)) to the top of the file as an HTML comment, for example:

```markdown
<!--
SPDX-License-Identifier: CC0-1.0 OR CC-BY-SA-4.0 
https://creativecommons.org/publicdomain/zero/1.0/
https://creativecommons.org/licenses/by-sa/4.0/
-->
```

**Comment by klardotsh** [comment]
More thinking about licenses since we're here: this dual-license stuff gets weird because translations are derivative works - I personally don't mind dual-licensing any docs I've contributed to (or relicensing them to CC0 entirely, because these days I'm tired of thinking about license interactions and compliance - I do it in my day job enough already), but we'd have to round up everyone who's in the `git log` for a file and get their OK to do such a thing.

Until then, the `SPDX-License-Identifier` would have to include `AND` which is a bit silly, but *technically* that's copyleft's rules: once something is CL, derivatives can't get _more_ permissive (whereas, for example, `MIT OR ISC` is valid in SPDX because the licenses are more or less equivalent). Sigh...

**Review by kdb424 — APPROVED** [review]

**Pull request merged**
