### PR TITLE
[rgb] fix set_rgb_fill method

### PR DESCRIPTION
**Pull request by crazyiop**
The code was wrongly iterating the neopixel, running `fill()` on every
individual pixels.

I suggested the change that was sucessfully tested by @ziptyze on discord.

### CODE REVIEW

**Review by kdb424 — APPROVED** [review]
Simple mistake, but huge issue. Thanks.

**Comment by xs5871** [comment]
This breaks the RGB extension. `RGB.pixels` is a list of pixel buffer objects, not a bare pixel buffer.
The original code is correct and working.

**Comment by crazyiop** [comment]
@xs5871 ha yes I have  read the code too quickly. I guess then that for some reason on @ziptyze board the line https://github.com/KMKfw/kmk_firmware/blob/90c4ce99f3ff781f8361f01c847ed0d60b037748/kmk/extensions/rgb.py#L123 did not correctly trigger...

**Comment by kdb424** [comment]
Welp. This is why we have a revert button. Coffee, then reviews >_>

**Pull request merged**
