### PR TITLE
reorganize docs into folders, fix links

### PR DESCRIPTION
**Pull request by patricksurry**
Reorganizes docs into folders following the getting started guide, fixing various broken links.

I also included an environment.yml and mkdocs.yml for local testing and link checking via mkdocs + mkdocs-material:
```
micromamba create -f environment.yml
mkdocs serve
```
then browse at http://127.0.0.1:8000/en/

It looks pretty good with almost no config and has language selector plus search for free 🔥   But these changes should also be fine with the existing website.

image

### CODE REVIEW

**Comment by claycooper** [comment]
Thanks for your work here. I'm going through what publishing the pages might look like and have started a conversation with the other reviewers about the direction for documentation.

**Comment by patricksurry** [comment]
i'm far from an expert, but github pages might even be viable for the docs pages themselves, and just link from the website?  i've used that with mkdocs before.

**Comment by claycooper** [comment]
I tried running the commands provided without success. I'm not familiar with micromamba and Google is not being a friend with that error.

```$ micromamba create -f environment.yml
warning  libmamba No 'channels' specified
error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ pip does not exist (perhaps a typo or a missing channel);
    └─ python does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
```

**Comment by patricksurry** [comment]
I think it's [this issue](https://github.com/mamba-org/mamba/issues/2550).   Try `micromamba config --add channels conda-forge`

**Comment by claycooper** [comment]
We've removed the non-English versions of the docs in #933 . Can you re-base to include those changes and other updates to docs that have happened over time? I'm also working on getting a theme closer to the current site's main color and adding a favicon and can push those to this PR. If you want to attempt that before I get to it, then go ahead.

**Pull request closed without merging**
