### PR TITLE
iris port to nicenano

### PR DESCRIPTION
**Pull request by kdb424**
Ported the Iris Rev 2 for the nice!nano. Needs tested on a real board, but testing on a bare PCB works great.

### CODE REVIEW

**Review by dzervas — APPROVED** [review]
LGTM!

**Comment by kdb424** [comment]
I'll be waiting on a report of a working board in case I got the pins incorrect. @klardotsh actually owns that board, hence why I am waiting on his review.

**Comment by klardotsh** [comment]
Holding this at least temporarily since I do indeed own two Irises (Irii?), one of which came home from the office when The World Ended (TM) and thus can be a donor board for testing this

**Comment by kdb424** [comment]
Closing as an automated tool can guarantee correctness for #189

**Pull request closed without merging**
