### PR TITLE
Add Support for SofleV2

### PR DESCRIPTION
**Pull request by ldsands**
Added support for SofleV2 using the SparkFun Pro Micro RP2040

### CODE REVIEW

**Comment by ldsands** [comment]
I am not sure how to format the files using the standard for the project. Any guidance there would be appreciated.

Anything else you need me to do, let me know.

**Comment by kdb424** [comment]
> I am not sure how to format the files using the standard for the project. Any guidance there would be appreciated.
> 
> Anything else you need me to do, let me know.

`make fix-isort fix-formatting test`. In general, this should auto format everything. If it formats *too* good, it's a bug, and we'll figure it out, but generally that works.

**Comment by ldsands** [comment]
Okay I think I got it all working. I wasn't familiar with pipenv, I usually use pyenv with venv for my environments. Let me know if there is anything else you need me to do.

**Review by kdb424 — APPROVED** [review]
Looks perfect. Good notes, have retailers, and code is clean. Assuming all tests pass, will merge. Thank you for your contribution!

**Pull request merged**
