### PR TITLE
7 segment display

### PR DESCRIPTION
**Pull request by daysgobye**

### CODE REVIEW

**Review by kdb424 — APPROVED** [review]
Leaving to @klardotsh for final review if he wants to do so, otherwise I'll merge if tests are clean.

**Comment by kdb424** [comment]
`make fix-isort` I think will resolve those issues.

**Comment by daysgobye** [comment]
sooo Now there are lots of changes but should be good

**Comment by kdb424** [comment]
It was a bit overreaching, but seems like they needed done anyways, and our makefile is overreaching. Yolo if it passes. For future tests `make test` will show you issues before a commit.

**Comment by klardotsh** [comment]
I'd love for this to be a generic driver/extension and not hard-coded to be layers-related, but I don't have the brain space to help design up such an API right now :shrug:

**Comment by kdb424** [comment]
Maybe worth changing the name to indicate what it does specifically? Having modules be specific can be a good thing to keep things simple, especially for things as simple as a seven segment display, but have different modules to load based on what you want it to do?

**Comment by kdb424** [comment]
Closed as requested.

**Pull request closed without merging**
