### PR TITLE
swapping control with cmd

### PR DESCRIPTION
**Pull request by masiullah**
Another qmk inspired feature which allows swapping control with cmd and vice versa
Helpful when using the keyboard on mac and windows

### CODE REVIEW

**Review by kdb424 — CHANGES_REQUESTED** [review]
I like the functionality, but I'd like to see a change in the name of the module as it sounds too broad, and may collide with others thoughts on what it does. Functionality wise, I think it looks great.

**Comment by masiullah** [comment]
> I like the functionality, but I'd like to see a change in the name of the module as it sounds too broad, and may collide with others thoughts on what it does. Functionality wise, I think it looks great.

Thanks. I agree the module name is too broad. I will change the name of the module to reflect exactly the feature it is performing at the moment
My thought was to add more keys in future to the same module which can swap other modifier keys and may be others could also add on to the same module if additional swap functionality are required

**Comment by kdb424** [comment]
If you can come up with a valid use case other than Mac/Other swap keys, I'm open to ideas. Otherwise, I may suggest something like mac_swap or something similar. I also use my keyboard on Mac/Linux, but I do all the hacking OS level for reasons, so I didn't bother with this sort of keyboard hacks, but I understand not everyone wants to, or can, do that.

**Comment by masiullah** [comment]
Honestly, I don't have any other valid use cases for swapping the modifiers or any other keys. Unless some one else can provide other valid cases modifying the module name will be the best option
I will rename the module to either mac_swap or cg_swap (control gui swap)

**Comment by kdb424** [comment]
Sounds great to me! Really appreciate the contribution, and that's a great feature. I did almost forget. Needs docs to go with it. Don't know how that slipped my mind.

**Comment by masiullah** [comment]
Sure, will also add docs for both the pull requests with at least basic information on usage

**Comment by kdb424** [comment]
Perfect. I'll do what I can do get them reviewed and merged this weekend if mergable, or at least give reasonable feedback.

**Review by kdb424 — APPROVED** [review]

**Pull request merged**
