### PR TITLE
Reduce key dictionary memory footprint

### PR DESCRIPTION
**Pull request by xs5871**
Instead of indexing `Key` objects that have multiple names by each individual name, index by the set of names. This reduces the size of the default key dictionary by a factor of between 2 and 3, and as result also reduces reallocations/defragmentation.
Instead of instantiating all module/extension keys by default, append them to the `maybe_key`-generator list.

### CODE REVIEW

**Comment by xs5871** [comment]
@klardotsh : maybe this fell through. Would you like to state an opinion?

**Comment by mali1741** [comment]
I noticed there's still code that's not adapted to maybe-make-key things, like sequences for example.

**Comment by xs5871** [comment]
If by sequences you're refering to `send_string`, correct. That is due for a refactor. If I missed some of the existing `KC.xxx` references, let me know.

**Comment by xs5871** [comment]
Ah, ok. Fixed it.

**Comment by claycooper** [comment]
Should we be concerned about the return of `make_key` changing the return type? I only see [one instance](https://github.com/KMKfw/kmk_firmware/blob/master/user_keymaps/klardotsh/klarank_featherm4.py#L83) in the codebase where the return of `make_key` is saved for later use in the keymap so it may not be a big deal except for people with custom modules/handlers in downstream forks.

**Comment by xs5871** [comment]
That's an interesting point. Concerned, no,
* it's not really a publicly documented method,
* in the past it was a wrapper around key object instanciation that automatically indexed those keys in the global dictonary `KC`,
* the keymap you pointed out is a meme example and doesn't even use the auto-index functionality; `make_key` isn't even necessary there.

The key object generation code has gone through some radical changes in the last year. The code was even more convoluted then it is now. It's still easy to lose sight of how everything fits together.
While I don't see concern for compatibility reasons, that specific line of code isn't a nice solution. We could move the tuple return from `make_key` into the generators. This PR isn't the end of key code refactoring, and `make_key` may go away entirely at some point.

**Review by claycooper — COMMENTED** [review]
Code ran without crashing, lowered memory as expected, and looks like a good move forward for improving keys.

**Review by claycooper — APPROVED** [review]

**Comment by xs5871** [comment]
So, I did some further tests and investigations, and it appears that some of my assumptions about memory management are not correct. I'll demote this PR to draft for now, but probably close it and open a new one with a better solution.

**Pull request closed without merging**
