### PR TITLE
Update oneshot.md

### PR DESCRIPTION
**Pull request by regicidalplutophage**
Updated documentation for updated Oneshot module

### CODE REVIEW

**Review by xs5871 — APPROVED** [review]
Waiting for formal approval of #704, then I'll merge both at the same time.

**Comment by xs5871** [comment]
I think you may have closed this accidentally.

**Comment by regicidalplutophage** [comment]
Yep, deleted my fork without thinking.

**Comment by xs5871** [comment]
Wait. Why did it close again?

**Comment by xs5871** [comment]
Oh, I think because I merged the branch you based the patch on, it's now parent-less.

**Pull request closed without merging**
