### PR TITLE
unit test fail may be caused by a stuck combo

### PR DESCRIPTION
**Pull request by xs5871**
Let's see if this still fails.

### CODE REVIEW

**Comment by xs5871** [comment]
may resolve #506
@Jawfish could you check with your abundance of different operating systems?

**Comment by Jawfish** [comment]
It passes on Arch/Ubuntu/macOS, but still fails on Windows. There is one less failure on Windows - `test_holdtap_chain` passes now.

**Comment by xs5871** [comment]
Hm. Not great, but it's something.
I think I remember the original author of the unit test mentioning the random loop of `keyboard_go` as "necessary to make it pass", but that's hardly a satisfactory explanation for what's going on.
Can we merge this as a step in the right direction, but keep #506 open?

**Review by Jawfish — APPROVED** [review]
I don't have a problem with it. I imagine most contributors will be running something Unix-based anyway (it passes on WSL, too)

**Review by kdb424 — APPROVED** [review]
I vote that we merge this. It works on "all" platforms if you count WSL, and honestly, that seems like a valid shim to me. If someone wants to offer a different fix later, awesome, but this is better than nothing, and is technically always available, much the same as "docker only runs on linux" even though people use it on other platforms *sorta technically they don't but whatever*.

**Pull request merged**
