### PR TITLE
Update Officially_Supported_Microcontrollers.md

### PR DESCRIPTION
**Pull request by xs5871**
remove nice!nano from the list of supported contollers.

### CODE REVIEW

**Comment by xs5871** [comment]
This PR may be solved/obsoleted by https://github.com/boardsource/bs-python.

**Comment by klardotsh** [comment]
given that my keyboard (keebio Iris) runs on a N!N I'm not 100% sure why we'd remove it from the list here, but I'll defer that decision to @kdb424 et al

**Comment by kdb424** [comment]
KMKpython is old, broken, and not working, which took that board with it. That said, bs-python is adding proper support back @klardotsh

**Comment by levpopov** [comment]
added #394 to address this

**Pull request closed without merging**
