### PR TITLE
Re-implement sequences as macro in a module

### PR DESCRIPTION
**Pull request by xs5871**

### CODE REVIEW

**Comment by xs5871** [comment]
Better macros. It's not *super* pretty, but it's good enough to be an improvement:
* It's a module. No unecessary code in core.
* Asynchronous. Doesn't lock the entire firmware, but it will buffer key events when a macro is running and replay them afterwards.
* Clean Interface. No more awkward double negative `no_press`/`no_release`.
* Unittestable.
* Unintentionally flexible. Effectively any code can be put in a macro now.
* Spellchecked documentation on the third try.

I'll purge the abomination that's the `sequences` code soonish. A couple of board configurations need refactoring, which I'm not looking forward to.

**Comment by xs5871** [comment]
Sometimes clicking the right button is hard.

**Review by regicidalplutophage — APPROVED** [review]
I like this a lot!

**Comment by anventia** [comment]
It seems like the docs have not been updated, and still shows the old Sequences, can this please be updated?

**Comment by claycooper** [comment]
New docs have been pushed to the website.

**Pull request merged**
