### PR TITLE
Updated directories and added links to keys.py

### PR DESCRIPTION
**Pull request by chemicalwill**
* linked named files for ease of access
* updated directories (ex. kmk/internal_state.py -> kmk/kmk_keyboard.py)

### CODE REVIEW

**Review by kdb424 — APPROVED** [review]

**Review by klardotsh — CHANGES_REQUESTED** [review]
I realize we're not super consistent about this currently, but in GitHub's Markdown renderer, `[\`kmk/keys.py\`](kmk/keys.py)` will always link to the correct branch (whatever the viewer is looking at) rather than forcibly referring to master via full HTTP link

**Comment by chemicalwill** [comment]
> I realize we're not super consistent about this currently, but in GitHub's Markdown renderer, `[\`kmk/keys.py`](kmk/keys.py)` will always link to the correct branch (whatever the viewer is looking at) rather than forcibly referring to master via full HTTP link

Very cool! I did not know this - I'm happy to update it later today

**Review by klardotsh — APPROVED** [review]
this is awesome, thank you!

**Comment by chemicalwill** [comment]
@klardotsh thank you! I am happy to help in any small way I can.

**Pull request merged**
